### ISSUE TITLE
Rendering issue on Drawing Concepts essay

### ISSUE THREAD

**Issue by gerwitz** [MaggieAppleton/maggieappleton.com#113]
This page has a rendering issue on Safari with the https://maggieappleton.com/drawinginvisibles1 in the "a few more" list. See [attached PDF](https://github.com/MaggieAppleton/maggieappleton.com/files/5754524/How.to.Draw.Invisible.Programming.Concepts.-.Part.One.pdf)

**Comment by texastoland** [comment]
The culprit looks like competing widths and heights overriding the images' intrinsic aspect ratios. The easiest fix looks like removing their `width: 100%` and optionally the padding from their parent `<div>`:

![image](https://user-images.githubusercontent.com/48431/109421291-b00a6200-79a4-11eb-9326-9511d784bb0e.png)

On an aside they're being embedded at full 800x800 instead of rendered size.

**Comment by MaggieAppleton** [comment]
Adjusted the CSS on these and should be all fixed. Tested it in safari and appears to be working as expected

![image](https://user-images.githubusercontent.com/5599295/120775626-49ed2800-c51b-11eb-90dc-ab8427820b2e.png)
